# Generated by Django 5.2.11 on 2026-03-01 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('normalized_url', models.URLField(unique=True)),
                ('geo', models.CharField(default='GH', max_length=32)),
                ('language', models.CharField(default='en', max_length=16)),
                ('device', models.CharField(default='desktop', max_length=16)),
                ('niche_label', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='seo.clientsite')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('client_position', models.IntegerField(blank=True, null=True)),
                ('visibility_score', models.FloatField(default=0.0)),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('competitor_urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_results', to='seo.auditrun')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('user', 'User'), ('extracted', 'Extracted'), ('ai', 'Ai'), ('hybrid', 'Hybrid')], default='extracted', max_length=16)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_sets', to='seo.auditrun')),
            ],
        ),
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('role', models.CharField(choices=[('client', 'Client'), ('competitor', 'Competitor')], max_length=16)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('html_hash', models.CharField(max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('raw_html_ref', models.CharField(blank=True, max_length=512, null=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_snapshots', to='seo.auditrun')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(max_length=64)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='med', max_length=8)),
                ('reason_text', models.TextField()),
                ('evidence_refs', models.JSONField(default=list)),
                ('expected_impact', models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='med', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='seo.auditrun')),
            ],
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(choices=[('FETCH_CLIENT', 'Fetch Client'), ('CLASSIFY', 'Classify'), ('KEYWORDS', 'Keywords'), ('SERP', 'Serp'), ('COMPETITORS', 'Competitors'), ('ANALYZE', 'Analyze'), ('FINALIZE', 'Finalize')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='seo.auditrun')),
            ],
        ),
        migrations.CreateModel(
            name='RunStepAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('worker_hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('run_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_records', to='seo.runstep')),
            ],
        ),
        migrations.CreateModel(
            name='SerpSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=64)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_snapshots', to='seo.auditrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='auditrun',
            index=models.Index(fields=['client_site', '-created_at'], name='seo_auditru_client__57a7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrun',
            index=models.Index(fields=['status', '-created_at'], name='seo_auditru_status_471387_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresult',
            index=models.Index(fields=['audit_run'], name='seo_keyword_audit_r_3f990d_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresult',
            index=models.Index(fields=['client_position'], name='seo_keyword_client__023746_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordresult',
            constraint=models.UniqueConstraint(fields=('audit_run', 'keyword'), name='uniq_run_keyword'),
        ),
        migrations.AddIndex(
            model_name='keywordsetversion',
            index=models.Index(fields=['audit_run', '-created_at'], name='seo_keyword_audit_r_5a8b66_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesnapshot',
            index=models.Index(fields=['audit_run', 'role'], name='seo_pagesna_audit_r_43958d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesnapshot',
            index=models.Index(fields=['url'], name='seo_pagesna_url_e398bd_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesnapshot',
            index=models.Index(fields=['html_hash'], name='seo_pagesna_html_ha_daa526_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['audit_run', 'priority'], name='seo_recomme_audit_r_bb1092_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['action_type'], name='seo_recomme_action__ccb498_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['audit_run', 'step_name'], name='seo_runstep_audit_r_b17267_idx'),
        ),
        migrations.AddIndex(
            model_name='runstep',
            index=models.Index(fields=['status'], name='seo_runstep_status_dbd2d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.UniqueConstraint(fields=('audit_run', 'step_name'), name='uniq_run_step'),
        ),
        migrations.AddIndex(
            model_name='runstepattempt',
            index=models.Index(fields=['run_step', '-attempt_no'], name='seo_runstep_run_ste_76eb75_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstepattempt',
            constraint=models.UniqueConstraint(fields=('run_step', 'attempt_no'), name='uniq_step_attempt_no'),
        ),
        migrations.AddIndex(
            model_name='serpsnapshot',
            index=models.Index(fields=['audit_run'], name='seo_serpsna_audit_r_dfde2a_idx'),
        ),
        migrations.AddIndex(
            model_name='serpsnapshot',
            index=models.Index(fields=['keyword'], name='seo_serpsna_keyword_494c14_idx'),
        ),
        migrations.AddIndex(
            model_name='serpsnapshot',
            index=models.Index(fields=['-fetched_at'], name='seo_serpsna_fetched_4d818e_idx'),
        ),
    ]
