# Generated by Django 5.2.11 on 2026-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='ai_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
