# Generated by Django 5.2.11 on 2026-03-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auditrun_ai_meta_auditrun_ai_summary'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagesnapshot',
            constraint=models.UniqueConstraint(fields=('audit_run', 'url', 'role'), name='uniq_run_url_role'),
        ),
    ]
