# Generated by Django 5.2.11 on 2026-03-10 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_pagesnapshot_uniq_run_url_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('prompt', models.TextField()),
                ('system', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_batches', to='seo.auditrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=16)),
                ('response', models.JSONField(blank=True, null=True)),
                ('response_raw', models.TextField(blank=True, default='')),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_seconds', models.FloatField(blank=True, null=True)),
                ('parse_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16, null=True)),
                ('parse_error', models.TextField(blank=True, default='')),
                ('recs_parsed', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('traceback_snippet', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_runs', to='seo.auditrun')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='seo.llmbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmbatch',
            index=models.Index(fields=['audit_run', 'provider'], name='seo_llmbatc_audit_r_a978c6_idx'),
        ),
        migrations.AddIndex(
            model_name='llmbatch',
            index=models.Index(fields=['created_at'], name='seo_llmbatc_created_cf1920_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrun',
            index=models.Index(fields=['audit_run', 'provider'], name='seo_llmrun_audit_r_3219c2_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrun',
            index=models.Index(fields=['batch'], name='seo_llmrun_batch_i_77a1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrun',
            index=models.Index(fields=['status'], name='seo_llmrun_status_9f9dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrun',
            index=models.Index(fields=['created_at'], name='seo_llmrun_created_cc32df_idx'),
        ),
    ]
