# Generated by Django 5.2.11 on 2026-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_llmbatch_llmrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrun',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
