# Generated by Django 5.2.11 on 2026-03-10 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_auditrun_last_reconciled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('run_started', 'Run Started'), ('step_success', 'Step Success'), ('step_failed', 'Step Failed'), ('run_complete', 'Run Complete'), ('run_failed', 'Run Failed')], max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='seo.auditrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='seo_notific_user_id_f4727a_idx'), models.Index(fields=['audit_run', '-created_at'], name='seo_notific_audit_r_985fa2_idx'), models.Index(fields=['user', 'read'], name='seo_notific_user_id_7a62c0_idx')],
            },
        ),
    ]
