# Generated by Django 5.2.11 on 2026-03-17 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_clientsite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsite',
            name='normalized_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clientsite',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name='clientsite',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_url'), name='uniq_user_normalized_url'),
        ),
        migrations.AddConstraint(
            model_name='clientsite',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='uniq_user_url'),
        ),
    ]
